import { useState, useEffect, useMemo } from 'react'
import { API } from '../lib/server'
import { useToast } from '../components/Toast'

interface DataFile {
  filename: string
  display_name: string
  size_bytes: number
  line_count: number
  created_at: string
}

interface FileGroup {
  display_name: string
  job_count: number
  size_bytes: number
  line_count: number
  latest_at: string
  filenames: string[]
}

// ---------------------------------------------------------------------------
// Curated dataset library
// ---------------------------------------------------------------------------

type DatasetFormat = 'instruction' | 'chat' | 'text'
type DatasetCategory = 'general' | 'coding' | 'reasoning' | 'math' | 'multilingual'

interface CuratedDataset {
  id: string
  name: string
  description: string
  goodFor: string       // short "best used for" phrase shown on card
  examples: string
  size: string
  large?: boolean       // show download size warning
  format: DatasetFormat
  category: DatasetCategory
  license: string
  url: string
  filename: string
}

const CURATED: CuratedDataset[] = [
  // ── General ────────────────────────────────────────────────────────────────
  {
    id: 'dolly-15k',
    name: 'Databricks Dolly 15k',
    description: '15k human-written pairs across brainstorming, open QA, summarisation, classification, and creative writing. Written entirely by Databricks employees — no GPT, no scraping.',
    goodFor: 'Solid general-purpose baseline · Customer-facing assistants · High quality over volume',
    examples: '15,011',
    size: '~3.5 MB',
    format: 'instruction',
    category: 'general',
    license: 'CC BY-SA 3.0',
    url: 'https://huggingface.co/datasets/databricks/dolly-15k/resolve/main/databricks-dolly-15k.jsonl',
    filename: 'dolly-15k.jsonl',
  },
  {
    id: 'alpaca-52k',
    name: 'Stanford Alpaca 52k',
    description: 'The classic self-instruct dataset from Stanford. 52k diverse instruction/response pairs generated from text-davinci-003. Broad task coverage and very widely used.',
    goodFor: 'General instruction following · Broad coverage · Good starting point for any domain',
    examples: '52,002',
    size: '~22 MB',
    format: 'instruction',
    category: 'general',
    license: 'CC BY-NC 4.0',
    url: 'https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json',
    filename: 'alpaca-52k.jsonl',
  },
  {
    id: 'alpaca-cleaned',
    name: 'Alpaca Cleaned 51k',
    description: 'A community-cleaned version of Stanford Alpaca — duplicates removed, bad examples filtered, hallucinated instructions fixed. Strictly better quality than the original.',
    goodFor: 'Same as Alpaca but cleaner · Use this over raw Alpaca if training from scratch',
    examples: '51,942',
    size: '~21 MB',
    format: 'instruction',
    category: 'general',
    license: 'CC BY-NC 4.0',
    url: 'https://raw.githubusercontent.com/gururise/AlpacaDataCleaned/main/alpaca_data_cleaned.json',
    filename: 'alpaca-cleaned.jsonl',
  },
  {
    id: 'alpaca-gpt4',
    name: 'Alpaca GPT-4 52k',
    description: 'Same prompts as Stanford Alpaca but answers re-generated by GPT-4. Noticeably higher response quality — more accurate, better structured, better tone.',
    goodFor: 'Higher quality baseline · More coherent responses · Better than standard Alpaca',
    examples: '52,002',
    size: '~24 MB',
    format: 'instruction',
    category: 'general',
    license: 'CC BY-NC 4.0',
    url: 'https://raw.githubusercontent.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM/main/data/alpaca_gpt4_data.json',
    filename: 'alpaca-gpt4.jsonl',
  },
  {
    id: 'lima-1k',
    name: 'LIMA 1k',
    description: 'Only 1,000 carefully hand-curated examples — yet competitive with much larger datasets. Proves quality > quantity. Great starting point when you don\'t have much data.',
    goodFor: 'Minimal data experiments · Quality over volume · Fast training iterations',
    examples: '1,000',
    size: '~1 MB',
    format: 'chat',
    category: 'general',
    license: 'CC BY-NC-SA 4.0',
    url: 'https://huggingface.co/datasets/GAIR/lima/resolve/main/train.jsonl',
    filename: 'lima-1k.jsonl',
  },
  {
    id: 'wizardlm-evol-70k',
    name: 'WizardLM Evol Instruct 70k',
    description: 'Instructions "evolved" by GPT-4 to be progressively harder and more complex. Produces models that handle multi-step and nuanced requests better than standard instruction data.',
    goodFor: 'Complex multi-step reasoning · Handling difficult follow-up questions · Professional assistants',
    examples: '70,000',
    size: '~50 MB',
    large: true,
    format: 'instruction',
    category: 'general',
    license: 'CC BY-NC 4.0',
    url: 'https://huggingface.co/datasets/WizardLM/WizardLM_evol_instruct_70k/resolve/main/alpaca_evol_instruct_70k.json',
    filename: 'wizardlm-evol-70k.jsonl',
  },
  // ── Coding ─────────────────────────────────────────────────────────────────
  {
    id: 'code-alpaca-20k',
    name: 'Code Alpaca 20k',
    description: 'Code-focused self-instruct dataset. Covers writing functions, debugging, explaining code, and refactoring across Python, JS, SQL, and more.',
    goodFor: 'Code writing & debugging · Explaining code · Multi-language support',
    examples: '20,022',
    size: '~9 MB',
    format: 'instruction',
    category: 'coding',
    license: 'CC BY-NC 4.0',
    url: 'https://raw.githubusercontent.com/sahil280114/codealpaca/master/data/code_alpaca_20k.json',
    filename: 'code-alpaca-20k.jsonl',
  },
  {
    id: 'evol-instruct-code-80k',
    name: 'Evol Instruct Code 80k',
    description: 'WizardCoder\'s training data — code tasks evolved to be progressively harder via GPT-4. Produces models that handle complex, multi-part programming problems well.',
    goodFor: 'Complex algorithms · Technical interviews · Advanced code generation',
    examples: '78,000',
    size: '~65 MB',
    large: true,
    format: 'instruction',
    category: 'coding',
    license: 'CC BY-NC 4.0',
    url: 'https://huggingface.co/datasets/nickrosh/Evol-Instruct-Code-80k-v1/resolve/main/EvolInstruct-Code-80k.json',
    filename: 'evol-instruct-code-80k.jsonl',
  },
  // ── Reasoning ──────────────────────────────────────────────────────────────
  {
    id: 'open-platypus',
    name: 'Open Platypus 25k',
    description: 'STEM and logic-focused data curated from 11 open datasets. Emphasises scientific reasoning, analysis, and structured argumentation with strong deduplication.',
    goodFor: 'STEM subjects · Logical analysis · Science & engineering assistants',
    examples: '24,926',
    size: '~15 MB',
    format: 'instruction',
    category: 'reasoning',
    license: 'CC BY-NC-SA 4.0',
    url: 'https://huggingface.co/datasets/garage-bAInd/Open-Platypus/resolve/main/Open-Platypus.json',
    filename: 'open-platypus.jsonl',
  },
  // ── Math ───────────────────────────────────────────────────────────────────
  {
    id: 'metamath-395k',
    name: 'MetaMathQA 395k',
    description: 'Math word problems rewritten from multiple angles (rephrasing, FOBAR, self-verification) to maximise reasoning coverage. Used to train MetaMath, which outperforms Llama on GSM8K.',
    goodFor: 'Arithmetic & algebra · Word problems · Finance & logistics calculations',
    examples: '395,000',
    size: '~200 MB',
    large: true,
    format: 'instruction',
    category: 'math',
    license: 'MIT',
    url: 'https://huggingface.co/datasets/meta-math/MetaMathQA/resolve/main/MetaMathQA-395K.json',
    filename: 'metamath-395k.jsonl',
  },
]

const CATEGORIES: { id: DatasetCategory | 'all'; label: string }[] = [
  { id: 'all',         label: 'All'         },
  { id: 'general',     label: 'General'     },
  { id: 'coding',      label: 'Coding'      },
  { id: 'reasoning',   label: 'Reasoning'   },
  { id: 'math',        label: 'Math'        },
  { id: 'multilingual',label: 'Multilingual'},
]

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function groupFiles(files: DataFile[]): FileGroup[] {
  const map = new Map<string, FileGroup>()
  for (const f of files) {
    const g = map.get(f.display_name)
    if (g) {
      g.job_count++
      g.filenames.push(f.filename)
      if (f.created_at > g.latest_at) g.latest_at = f.created_at
    } else {
      map.set(f.display_name, {
        display_name: f.display_name,
        job_count: 1,
        size_bytes: f.size_bytes,
        line_count: f.line_count,
        latest_at: f.created_at,
        filenames: [f.filename],
      })
    }
  }
  return Array.from(map.values())
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function DataPage({ onDataAdded }: { onDataAdded?: () => void }) {
  const [files, setFiles] = useState<DataFile[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const { addToast } = useToast()
  const [preview, setPreview] = useState<{ group: FileGroup; records: object[] } | null>(null)
  const [previewLoading, setPreviewLoading] = useState(false)

  // Dataset library state
  const [libraryOpen, setLibraryOpen] = useState(false)
  const [activeCategory, setActiveCategory] = useState<DatasetCategory | 'all'>('all')
  const [downloading, setDownloading] = useState<Record<string, 'idle' | 'downloading' | 'done' | 'error'>>({})
  const [downloadError, setDownloadError] = useState<string | null>(null)
  const [customUrl, setCustomUrl] = useState('')
  const [customFilename, setCustomFilename] = useState('')
  const [customDownloading, setCustomDownloading] = useState(false)

  const visibleDatasets = activeCategory === 'all'
    ? CURATED
    : CURATED.filter(d => d.category === activeCategory)

  const groups = useMemo(() => groupFiles(files), [files])

  async function fetchFiles() {
    setLoading(true)
    setError(null)
    try {
      const resp = await fetch(`${API}/data/files`)
      if (!resp.ok) throw new Error(resp.statusText)
      setFiles(await resp.json())
    } catch (err) {
      setError(String(err))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchFiles() }, [])

  async function openPreview(group: FileGroup) {
    setPreviewLoading(true)
    setPreview({ group, records: [] })
    try {
      const resp = await fetch(`${API}/data/files/${encodeURIComponent(group.filenames[0])}/preview`)
      if (!resp.ok) throw new Error((await resp.json()).detail ?? resp.statusText)
      const data = await resp.json()
      setPreview({ group, records: data.records })
    } catch (err) {
      setPreview({ group, records: [] })
      setError(`Preview failed: ${String(err)}`)
    } finally {
      setPreviewLoading(false)
    }
  }

  async function deleteGroup(group: FileGroup) {
    if (!window.confirm(
      `Delete all ${group.job_count} cop${group.job_count === 1 ? 'y' : 'ies'} of "${group.display_name}"?\n\nCompleted training jobs and their models will not be affected.`
    )) return
    try {
      for (const filename of group.filenames) {
        const resp = await fetch(`${API}/data/files/${encodeURIComponent(filename)}`, { method: 'DELETE' })
        if (!resp.ok) throw new Error((await resp.json()).detail ?? resp.statusText)
      }
      setFiles(prev => prev.filter(f => !group.filenames.includes(f.filename)))
    } catch (err) {
      setError(`Delete failed: ${String(err)}`)
    }
  }

  async function downloadDataset(dataset: CuratedDataset) {
    setDownloading(prev => ({ ...prev, [dataset.id]: 'downloading' }))
    setDownloadError(null)
    try {
      const resp = await fetch(`${API}/data/fetch`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: dataset.url, filename: dataset.filename }),
      })
      if (!resp.ok) throw new Error((await resp.json()).detail ?? resp.statusText)
      setDownloading(prev => ({ ...prev, [dataset.id]: 'done' }))
      addToast('success', `${dataset.name} downloaded`)
      onDataAdded?.()
      fetchFiles()
    } catch (err) {
      setDownloading(prev => ({ ...prev, [dataset.id]: 'error' }))
      setDownloadError(`Failed to download ${dataset.name}: ${String(err)}`)
      addToast('error', `Failed to download ${dataset.name}`)
    }
  }

  async function downloadCustom() {
    if (!customUrl.trim()) return
    const filename = customFilename.trim() || customUrl.split('/').pop() || 'dataset.jsonl'
    setCustomDownloading(true)
    setDownloadError(null)
    try {
      const resp = await fetch(`${API}/data/fetch`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: customUrl.trim(), filename }),
      })
      if (!resp.ok) throw new Error((await resp.json()).detail ?? resp.statusText)
      setCustomUrl('')
      setCustomFilename('')
      addToast('success', 'Dataset downloaded')
      onDataAdded?.()
      fetchFiles()
    } catch (err) {
      setDownloadError(`Download failed: ${String(err)}`)
      addToast('error', 'Download failed')
    } finally {
      setCustomDownloading(false)
    }
  }

  return (
    <div className="p-8 max-w-3xl mx-auto">
      <h2 className="text-xl font-semibold mb-1">Training Data</h2>
      <p className="text-sm text-gray-400 mb-8">
        All <code className="bg-gray-800 px-1 rounded text-gray-200">.jsonl</code> files uploaded for fine-tuning.
      </p>

      {error && (
        <div className="mb-4 p-4 bg-red-950 border border-red-700 rounded-xl text-sm text-red-300">
          {error}
        </div>
      )}

      {loading ? (
        <div className="text-sm text-gray-500">Loading…</div>
      ) : groups.length === 0 ? (
        <div className="text-sm text-gray-500 text-center mt-16">
          No training files yet. Upload a <code className="bg-gray-800 px-1 rounded">.jsonl</code> file on the Training page.
        </div>
      ) : (
        <>
          <p className="text-xs text-gray-500 mb-3">
            Deleting a file does not affect completed training jobs or their models.
          </p>
          <div className="space-y-2">
            {groups.map(g => (
              <div
                key={g.display_name}
                className="flex items-center gap-4 p-4 bg-gray-900 border border-gray-800 rounded-xl text-sm"
              >
                <div className="flex-1 min-w-0">
                  <p className="text-gray-200 font-medium truncate">{g.display_name}</p>
                  <p className="text-xs text-gray-500 mt-0.5">
                    {g.line_count} example{g.line_count !== 1 ? 's' : ''} · {formatSize(g.size_bytes)}
                    {' · '}
                    <span className={g.job_count > 1 ? 'text-indigo-400' : ''}>
                      Used in {g.job_count} training job{g.job_count !== 1 ? 's' : ''}
                    </span>
                    {' · '}
                    {new Date(g.latest_at).toLocaleString()}
                  </p>
                </div>
                <button
                  onClick={() => openPreview(g)}
                  className="px-3 py-1.5 text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 rounded-lg transition-colors shrink-0"
                >
                  Preview
                </button>
                <button
                  onClick={() => deleteGroup(g)}
                  title="Delete file copies — does not affect completed training jobs"
                  className="text-gray-500 hover:text-red-400 transition-colors text-base shrink-0"
                >
                  🗑
                </button>
              </div>
            ))}
          </div>
        </>
      )}

      {/* Dataset library */}
      <div className="mt-10">
        <button
          onClick={() => setLibraryOpen(o => !o)}
          className="flex items-center gap-2 text-sm font-semibold text-gray-300 hover:text-white transition-colors w-full"
        >
          <span className={`text-xs transition-transform duration-150 ${libraryOpen ? 'rotate-90' : ''}`}>▶</span>
          Dataset Library
          <span className="text-xs font-normal text-gray-500">{CURATED.length} curated datasets</span>
          <a
            href="https://huggingface.co/datasets"
            target="_blank"
            rel="noopener noreferrer"
            onClick={e => e.stopPropagation()}
            className="ml-auto text-xs text-indigo-400 hover:text-indigo-300 transition-colors"
          >
            Browse HuggingFace →
          </a>
        </button>

        {libraryOpen && (
          <div className="mt-4">
            {downloadError && (
              <div className="mb-3 p-3 bg-red-950 border border-red-700 rounded-xl text-sm text-red-300">
                {downloadError}
              </div>
            )}

            {/* Category tabs */}
            <div className="flex gap-1 mb-4 flex-wrap">
              {CATEGORIES.map(cat => {
                const count = cat.id === 'all' ? CURATED.length : CURATED.filter(d => d.category === cat.id).length
                if (count === 0) return null
                return (
                  <button
                    key={cat.id}
                    onClick={() => setActiveCategory(cat.id)}
                    className={`px-3 py-1 text-xs font-medium rounded-full transition-colors ${
                      activeCategory === cat.id
                        ? 'bg-indigo-600 text-white'
                        : 'bg-gray-800 text-gray-400 hover:text-gray-200'
                    }`}
                  >
                    {cat.label}
                    {cat.id !== 'all' && count > 0 && (
                      <span className="ml-1 opacity-60">{count}</span>
                    )}
                  </button>
                )
              })}
            </div>

            {/* Dataset cards */}
            <div className="space-y-2">
              {visibleDatasets.length === 0 ? (
                <p className="text-sm text-gray-500 py-4 text-center">No datasets in this category yet.</p>
              ) : visibleDatasets.map(ds => {
                const state = downloading[ds.id] ?? 'idle'
                return (
                  <div key={ds.id} className="p-4 bg-gray-900 border border-gray-800 rounded-xl text-sm">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap mb-1">
                          <p className="font-medium text-gray-200">{ds.name}</p>
                          <span className="px-1.5 py-0.5 bg-gray-800 text-gray-400 text-xs rounded font-mono">{ds.format}</span>
                          <span className="px-1.5 py-0.5 bg-gray-800/50 text-gray-500 text-xs rounded">{ds.license}</span>
                        </div>
                        <p className="text-xs text-gray-500 leading-relaxed">{ds.description}</p>
                        <p className="text-xs text-indigo-400/70 mt-1.5">Good for: {ds.goodFor}</p>
                        <p className="text-xs text-gray-500 mt-1 flex items-center gap-2">
                          <span>{ds.examples} examples · {ds.size}</span>
                          {ds.large && (
                            <span className="px-1.5 py-0.5 bg-amber-900/40 text-amber-500 rounded text-xs font-medium">⚠ Large download</span>
                          )}
                        </p>
                      </div>
                      <button
                        onClick={() => (state === 'idle' || state === 'error') && downloadDataset(ds)}
                        disabled={state === 'downloading'}
                        className={`flex-shrink-0 px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                          state === 'done'
                            ? 'bg-green-900/50 text-green-400 border border-green-800 cursor-default'
                            : state === 'error'
                              ? 'bg-red-900/50 text-red-400 border border-red-800 hover:bg-red-900'
                              : state === 'downloading'
                                ? 'bg-gray-800 text-gray-500 cursor-not-allowed'
                                : 'bg-indigo-600 hover:bg-indigo-500 text-white'
                        }`}
                      >
                        {state === 'done' ? '✓ Saved' : state === 'error' ? 'Retry' : state === 'downloading' ? 'Downloading…' : 'Download'}
                      </button>
                    </div>
                  </div>
                )
              })}
            </div>

            {/* Custom URL */}
            <div className="mt-3 p-4 bg-gray-900 border border-gray-800 rounded-xl">
              <p className="text-xs font-medium text-gray-400 mb-2">Custom URL <span className="text-gray-500 font-normal">— any JSONL or JSON array</span></p>
              <div className="space-y-2">
                <input
                  value={customUrl}
                  onChange={e => setCustomUrl(e.target.value)}
                  placeholder="https://…"
                  className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-xs text-gray-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
                <div className="flex gap-2">
                  <input
                    value={customFilename}
                    onChange={e => setCustomFilename(e.target.value)}
                    placeholder="filename.jsonl (optional)"
                    className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-3 py-1.5 text-xs text-gray-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                  <button
                    onClick={downloadCustom}
                    disabled={!customUrl.trim() || customDownloading}
                    className="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 text-white text-xs font-medium rounded-lg transition-colors"
                  >
                    {customDownloading ? 'Downloading…' : 'Download'}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Preview modal */}
      {preview && (
        <div
          className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4"
          onClick={() => setPreview(null)}
        >
          <div
            className="bg-gray-900 border border-gray-700 rounded-2xl w-full max-w-2xl max-h-[80vh] flex flex-col"
            onClick={e => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-800">
              <div>
                <p className="text-sm font-semibold text-gray-200">{preview.group.display_name}</p>
                <p className="text-xs text-gray-500 mt-0.5">First 5 examples</p>
              </div>
              <button
                onClick={() => setPreview(null)}
                className="text-gray-500 hover:text-gray-200 text-lg leading-none transition-colors"
              >
                ✕
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-5 space-y-3">
              {previewLoading ? (
                <p className="text-sm text-gray-500">Loading…</p>
              ) : preview.records.length === 0 ? (
                <p className="text-sm text-gray-500">No records found.</p>
              ) : (
                preview.records.map((rec, i) => (
                  <div key={i} className="bg-gray-950 border border-gray-800 rounded-xl p-3">
                    <p className="text-xs text-gray-500 mb-1.5">Example {i + 1}</p>
                    <pre className="text-xs text-gray-300 whitespace-pre-wrap overflow-x-auto">
                      {JSON.stringify(rec, null, 2)}
                    </pre>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
